language: cpp


# env:
#   - V=0.21.0
#   - V=0.20.0


services:
  - mysql

script: bazel test  //test:server_test

install:
  - OS=linux
  - ARCH=x86_64
  - sudo apt-get install openjdk-8-jdk
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install bazel

  
