language: cpp


# env:
#   - V=0.21.0
#   - V=0.20.0


services:
  - mysql

script: ./install.sh 

install:
  - OS=linux
  - ARCH=x86_64
  - sudo apt-get install openjdk-8-jdk
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install bazel
  - chmod +x install.sh

  
# after_success: true

#after_script前5句是把部署分支的.git文件夹保护起来，用于保留历史部署的commit日志，否则部署分支永远只有一条commit记录。
#命令里面的变量都是在Travis CI里配置过的。
# after_script:
#   - git clone https://${GH_REF} .temp
#   - cd .temp
#   - git checkout gh-pages
#   - cd ../
#   - mv .temp/.git dist
#   - cd dist
#   - git config user.name "${U_NAME}"
#   - git config user.email "${U_EMAIL}"
#   - git add .
#   - git commit -m ":construction_worker:- Build & Deploy by Travis CI"
#   - git push --force --quiet "https://${Travis_Token}@${GH_REF}" gh-pages:${D_BRANCH}

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master


before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name generaltune
  - git config --local user.email 577174042@qq.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: b77082c8023d919aeab65152605f7d64831cbe36
  file: src/client 
  skip_cleanup: true


# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true
